
GET https://netflix-clone-demo-2022.herokuapp.com/

###
GET https://netflix-clone-demo-2022.herokuapp.com/users


###

GET https://netflix-clone-demo-2022.herokuapp.com/movies/list

###
POST https://netflix-clone-demo-2022.herokuapp.com/movies/list/add
content-type: application/json

{
    "id": 9,
    "title": "Titans"
}
###

POST https://netflix-clone-demo-2022.herokuapp.com/movies/list/remove
content-type: application/json

 {
    "id": 8,
    "title" : "movie 4"
    }

###

GET https://netflix-clone-demo-2022.herokuapp.com/movies/netflixoriginals


####

GET https://netflix-clone-demo-2022.herokuapp.com/movies/netflixoriginals/random


####

GET https://netflix-clone-demo-2022.herokuapp.com/movies?id=580489

###

POST https://netflix-clone-demo-2022.herokuapp.com/users/login
content-type: application/json

{
    "email": "mohammed@gmail.com",
    "password": "mohammed123456"
}