
GET http://localhost:5000/

###
GET http://localhost:5000/users


###

GET http://localhost:5000/movies/list

###
POST http://localhost:5000/movies/list/add
content-type: application/json

{
    "id": 9,
    "title": "Titans"
}
###

POST http://localhost:5000/movies/list/remove
content-type: application/json

 {
    "id": 8,
    "title" : "movie 4"
    }

###

GET http://localhost:5000/movies/netflixOriginals


####

POST http://localhost:5000/users/login
content-type: application/json

{
    "email": "noha@gmmail.com",
    "password": "noha123456"
}