GET http://localhost:5000/

###
GET http://localhost:5000/users


###

GET http://localhost:5000/movies

###
POST http://localhost:5000/movies
content-type: application/json

{
    "id": "8",
    "title": "Finch"
}

###
POST http://localhost:5000/users/login
content-type: application/json

{
    "email": "noha@gmmail.com",
    "password": "noha123456"
}